DROP TABLE AnalyzerWorkData
DROP TABLE Analyzers
DROP TABLE Analyses
DROP TABLE SampleTypes
DROP TABLE OrderStatusHistory
DROP TABLE Statuses
DROP TABLE ServiceOrderLaborants
DROP TABLE ServiceOrdersServices
DROP TABLE ServiceOrders
DROP TABLE ListWeeklyDiscounts
DROP TABLE ServiceLaboranten
DROP TABLE Services
DROP TABLE VacationPayments
DROP TABLE SicknessPayments
DROP TABLE WorkPayments
DROP TABLE VacationPaymentStatuses
DROP TABLE SicknessPaymentStatuses
DROP TABLE WorkPaymentStatuses
DROP TABLE EmployeeStatusHistory
DROP TABLE InventoryTransactions
DROP TABLE TransactionTypes
DROP TABLE Deliveries
DROP TABLE LabOrderStatusHistory
DROP TABLE LabOrderStatuses
DROP TABLE LabOrderInventory
DROP TABLE LabOrders
DROP TABLE SuppliersInventory
DROP TABLE Inventory
DROP TABLE InventoryTypes
DROP TABLE Suppliers
DROP TABLE WorkExecutionHistory
DROP TABLE PerformersOrders
DROP TABLE Performers
DROP TABLE PerformerTypes
DROP TABLE BuchhalterAccountingSoftware
DROP TABLE BuchhalterAccountingSpecialties
DROP TABLE SoftwarePayments
DROP TABLE SoftwareTenancyHistory
DROP TABLE TenancyTerms
DROP TABLE AccountingSoftware
DROP TABLE AccountingSpecialties
DROP TABLE Buchhalters
DROP TABLE PatientPayments
DROP TABLE OrganizationPayments
DROP TABLE EmployeePayments
DROP TABLE PaymentSendActs
DROP TABLE PaymentsSend
DROP TABLE PaymentsRecieveAct
DROP TABLE PaymentsRecieve
DROP TABLE PaymentsStatusHistory
DROP TABLE Payments
DROP TABLE PaymentMethods
DROP TABLE PaymentStatuses
DROP TABLE OrganizationRequisites
DROP TABLE PatientRequisites
DROP TABLE EmployeeRequisites
DROP TABLE Requisites
DROP TABLE AdministratorAssignedTasks
DROP TABLE TaskReports
DROP TABLE TaskReportStatuses
DROP TABLE TaskStatusHistory
DROP TABLE TaskStatuses
DROP TABLE AdministratorTasks
DROP TABLE Administratoren
DROP TABLE AdministratorRoles
DROP TABLE Laboranten
DROP TABLE EmployeeSalaryHistory
DROP TABLE Employees
DROP TABLE Disabilities
DROP TABLE EmployeeStatus
DROP TABLE WorkSchedule
DROP TABLE WorkShift
DROP TABLE WorkExperience
DROP TABLE AdditionalQualifications
DROP TABLE Certification
DROP TABLE Education
DROP TABLE EmployeeInfo
DROP TABLE HealthMonitoring
DROP TABLE Insurance
DROP TABLE Feedback
DROP TABLE Patients
DROP TABLE PatientsInfo
DROP TABLE InsuranceCompanies
DROP TABLE Organizations
DROP TABLE UserLoginHistory
DROP TABLE UserCredentials
DROP TABLE Users
DROP TABLE WeeklyDiscounts
DROP TABLE DiscountTargets
DROP TABLE DiscountPeriods
DROP TABLE OfficeLocations
DROP TABLE OfficeTypes
DROP TABLE OurRequisites
DROP TABLE Properties
DROP TABLE PropertyType
DROP TABLE PostalCodes
DROP TABLE Streets
DROP TABLE Districts
DROP TABLE Cities
DROP TABLE Regions
DROP TABLE Countries
DROP TABLE Continents